# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy ULA AzureWebApp - app-cv-portalvalidacion-ula-prod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://lottus.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_d6d2a43785264101a7d87ca0564e236f }}
        password: ${{ secrets.AzureAppService_ContainerPassword_7821cf1fea4740e7825b69a731f3c65a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: lottus.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d6d2a43785264101a7d87ca0564e236f }}/lottus/cv-portalvalidacion:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'app-cv-portalvalidacion-ula-prod'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5cd359e39c2746768804313ddc9108fc }}
        images: 'lottus.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d6d2a43785264101a7d87ca0564e236f }}/lottus/cv-portalvalidacion:${{ github.sha }}'
